[build]
  # This is a static site, no build process needed
  publish = "."
  command = "echo 'Static site - no build needed'"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for single page application behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.tailwindcss.com https://unpkg.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.tailwindcss.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: http:; connect-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Compress files
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Encoding = "gzip"

# Enable Hebrew language support
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Language = "he"
    
# Form handling (if using Netlify forms)
[forms]
  settings = true
